theme: jekyll-theme-cayman

title: "Shimosyan's portfolio" # cspell: disable-line
description: "Corporate Engineer "

lang: "ja"
show_downloads: false
google_analytics: "G-EW7Z0Z4KLX"

github:
  is_project_page: true
  repository_url: "https://github.com/shimosyan"
